"""Shared geometry contracts independent from rendering and persistence."""

from app.geometry.coordinates import (
    CanonicalCoordinateSystem,
    CanonicalPoint,
    WallCoordinateError,
)
from app.geometry.walls import (
    CanonicalWall,
    CanonicalWallCandidate,
    NormalizedWallGeometry,
    RawPixelPoint,
    RawPixelWall,
    normalize_wall_coordinates,
)
from app.geometry.canonical import (
    CanonicalDocumentWall,
    CanonicalFloor,
    CanonicalGeometryDocument,
    CanonicalGeometryError,
    CanonicalRoom,
    CanonicalRoute,
    CanonicalRoutePoint,
    CanonicalSymbol,
    build_canonical_geometry,
    canonical_geometry_from_dict,
)
from app.geometry.canonical_extension import (
    CanonicalExtensionV2,
    CanonicalOpening,
    CanonicalPanel,
    CanonicalPanelBounds,
    CanonicalRouteDetail,
    CanonicalSymbolBounds,
    CanonicalSymbolDetail,
    SourcePlaneReference,
    adapt_reviewed_candidate_to_canonical,
    canonical_extension_from_dict,
    compose_canonical_view,
)

__all__ = (
    "CanonicalCoordinateSystem",
    "CanonicalPoint",
    "CanonicalWall",
    "CanonicalWallCandidate",
    "NormalizedWallGeometry",
    "RawPixelPoint",
    "RawPixelWall",
    "WallCoordinateError",
    "normalize_wall_coordinates",
    "CanonicalDocumentWall",
    "CanonicalFloor",
    "CanonicalGeometryDocument",
    "CanonicalGeometryError",
    "CanonicalRoom",
    "CanonicalRoute",
    "CanonicalRoutePoint",
    "CanonicalSymbol",
    "build_canonical_geometry",
    "canonical_geometry_from_dict",
    "CanonicalExtensionV2",
    "CanonicalOpening",
    "CanonicalPanel",
    "CanonicalPanelBounds",
    "CanonicalRouteDetail",
    "CanonicalSymbolBounds",
    "CanonicalSymbolDetail",
    "SourcePlaneReference",
    "adapt_reviewed_candidate_to_canonical",
    "canonical_extension_from_dict",
    "compose_canonical_view",
)
